### ISSUE TITLE
Create .gitignore 

### ISSUE THREAD

**Issue by yashLadha** [TarunISCO/Dnet#1]
gitignore file should ignore the intellij folders as well as python modules.

**Comment by JohnHillegass** [comment]
Grabs !

**Comment by hydeenoble** [comment]
is the issue labeled "Hacktoberfest" resolved??

**Comment by yashLadha** [comment]
@JohnHillegass  now is it ok :laughing:

**Comment by yashLadha** [comment]
@hydeenoble it is assigned to @TarunISCO so he is now working on it.. :smile:
